GradePredictorApp/app/__init__.py
import os
import pandas as pd
import sys
import predictiveModelBuilding
from flask_api import FlaskAPI
from flask import render_template
from predictiveModelBuilding import PredictiveModelBuilding
from config import app_config
from sklearn.externals import joblib
from flask import request, abort, jsonify
from app.predictions import predictions
from flask_wtf.csrf import CSRFProtect,generate_csrf


csrf = CSRFProtect()
def create_app(config_name):
    """this method will initialise the flask API instance """

    if os.getenv('CIRCLECI'):
        app = FlaskAPI(__name__)
        app.config.update(
            SECRET_KEY=os.getenv('SECRET_KEY')
        )
    else:
        app = FlaskAPI(__name__, instance_relative_config=True)
        app.config.from_object(app_config[config_name])
        app.config.from_pyfile('config.py')
    csrf.init_app(app)
    from .predictions import predictions as predictions_blueprint
    app.register_blueprint(predictions_blueprint)
    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)
    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', title='Forbidden'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html', title='Page Not Found'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('errors/500.html', title='Server Error'), 500

    @app.errorhandler(400)
    def internal_server_error(error):
        return render_template('errors/400.html', title='Server Error'), 400
    return app

GradePredictorApp/app/home/__init__.py
from flask import Blueprint
home = Blueprint('home', __name__)
from . import views

GradePredictorApp/app/home/views.py
from flask import request, abort, jsonify, url_for,render_template
from . import home
@home.route('/')
def homepage():
    return render_template('home/index.html')

GradePredictorApp/app/predictions/__init__.py
import sys
from flask import Blueprint
predictions = Blueprint('predictions', __name__)
from . import views

GradePredictorApp/app/predictions/views.py
import sys
import app
import json
import pandas as pd
from sklearn.externals import joblib
reload(sys)
sys.setdefaultencoding('utf8')
from predictiveModelBuilding import PredictiveModelBuilding
import predictiveModelBuilding
from flask import request, abort, jsonify, url_for, render_template,redirect
from . import predictions


@predictions.route('/predictions/predict_form/', methods=['GET'])
def predict_form():
    """ this is the main route to handle the predict form"""
    return render_template('predictions/forms.html')

@predictions.route('/predictions/predict/', methods=['GET', 'POST'])
def predict():
    """

    the main method use to predict

    """
    if request.method == 'GET':
        abort(403)
    else :
        predictives_models = []
        predicted_grades = {}
        model_names = ['FM', 'FSTA', 'FD', 'FSDC', 'FSEG', 'FPSE', 'FT']
        app_floder = predictions.root_path.replace('predictions', 'static/')
        for filename in model_names:
            model = joblib.load(app_floder+'/classes/'+filename+'.pkl')
            predictives_models.append(model)

        new_student = request.data
        new_student_data = pd.DataFrame(new_student, columns=new_student.keys(), index=range(1))
        for dept, name in zip(predictives_models, model_names):
            predicted_grade = dept.predict_new(new_student_data)
            final_grade = predicted_grade[0]
            predicted_grades[name] = final_grade*100
        response = jsonify(predicted_grades)
        response.status_code = 200
        return response


@predictions.route('/predictions/results/<results>', methods=['GET'])
def view_results(results):
    """ display the predicted results """
    results = json.loads(results)
    return render_template('predictions/results.html', results=results)

GradePredictorApp/app/templates/base.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--
    Document Title
    =============================================
    -->
    <title>{% block title %}{% endblock %} </title>
    <!--
    Favicons
    =============================================
    -->

    <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename="images/favicons/apple-icon-57x57.png")}}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename="images/favicons/apple-icon-60x60.png")}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename="images/favicons/apple-icon-72x72.png")}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename="images/favicons/apple-icon-76x76.png")}}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename="images/favicons/apple-icon-114x114.png")}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename="images/favicons/apple-icon-120x120.png")}}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename="images/favicons/apple-icon-144x144.png")}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename="images/favicons/apple-icon-152x152.png")}}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename="images/favicons/apple-icon-180x180.png")}}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename="images/favicons/android-icon-192x192.png")}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename="images/favicons/favicon-32x32.png")}}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename="images/favicons/favicon-96x96.png")}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename="images/favicons/favicon-16x16.png")}}">
    <link rel="manifest" href="{{ url_for('static', filename="manifest.json")}}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ url_for('static', filename="images/favicons/ms-icon-144x144.png")}}">
    <meta name="theme-color" content="#ffffff">
    <!--
    Stylesheets
    =============================================
    -->
    <!-- Default stylesheets-->
    <link href="{{ url_for('static', filename="lib/bootstrap/dist/css/bootstrap.min.css")}}" rel="stylesheet">
    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/animate.css/animate.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/components-font-awesome/css/font-awesome.min.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/et-line-font/et-line-font.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/flexslider/flexslider.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/owl.carousel/dist/assets/owl.theme.default.min.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/magnific-popup/dist/magnific-popup.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/magnific-popup/dist/magnific-popup.css")}}" rel="stylesheet">
    <link href="{{ url_for('static', filename="lib/simple-text-rotator/simpletextrotator.css")}}" rel="stylesheet">
    <!-- Main stylesheet and color file-->
    <link href="{{ url_for('static', filename="css/style.css")}}" rel="stylesheet">
    <link id="color-scheme" href="{{ url_for('static', filename="css/colors/default.css")}}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    {% endblock %}
  </head>
   <body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
    <main>
      <div class="page-loader">
        <div class="loader">Loading...</div>
      </div>
      <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="{{url_for('home.homepage')}}">Grade Predictor</a>
          </div>
          <div class="collapse navbar-collapse" id="custom-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{{url_for('home.homepage')}}">Home</a></li>
              <li><a href="{{url_for('home.homepage')}}#about">A Propos</a></li>
              <li><a href="{{url_for('home.homepage')}}#services">Notre Approche</a></li>
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}{% endblock %}
      {% block footer %}
    <hr class="divider-d">
        <footer class="footer bg-dark">
          <div class="container">
            <div class="row">
              <div class="col-sm-6">
                <p class="copyright font-alt">&copy; 2017&nbsp;<a href="http://espoir.me">espy mur</a>, All Rights Reserved</p>
              </div>
              <div class="col-sm-6">
                <div class="footer-social-links"><a href="https://github.com/espoirMur" target="_blank" ><i class="fa fa-github"></i></a><a href="https://twitter.com/EspyMur" target="_blank" ><i class="fa fa-twitter"></i></a><a href="http://espoir.me" target="_blank" ><i class="fa fa-dribbble"></i></a><a href="https://stackoverflow.com/users/4683950/espoir-murhabazi" target="_blank" ><i class="fa fa-stack-overflow"></i></a>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </div>
      <div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>
    </main>
      {% endblock %}
      <!--
    JavaScripts
    =============================================
    -->
    <script src="{{ url_for('static', filename="lib/jquery/dist/jquery.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/bootstrap/dist/js/bootstrap.min.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/wow/dist/wow.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/isotope/dist/isotope.pkgd.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/imagesloaded/imagesloaded.pkgd.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/flexslider/jquery.flexslider.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/owl.carousel/dist/owl.carousel.min.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/smoothscroll.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/magnific-popup/dist/jquery.magnific-popup.js")}}"></script>
    <script src="{{ url_for('static', filename="lib/simple-text-rotator/jquery.simple-text-rotator.min.js")}}"></script>
    <script src="{{ url_for('static', filename="js/plugins.js")}}"></script>
    <script src="{{ url_for('static', filename="js/main.js")}}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap3-typeahead.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/index.js')}}"></script>
  </body>
</html>

GradePredictorApp/app/templates/busses.html
<table style="width:100%">
    <tr>
        <th>Bus Type</th>
        <th>Bus Information</th>
    </tr>

    {% for bus, info  in jnjbus_info %}
        <tr>


            <td>{{bus}}</td>
            <td>{{info}}</td>
        </tr>
        {% endfor %}
</table>

GradePredictorApp/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
      <section class="home-section home-parallax home-fade home-full-height" id="home">
        <div class="hero-slider">
          <ul class="slides">
            <li class="bg-dark-30 bg-dark" style="background-image:{{url_for('static', filename='/images/section-8.jpg')}};">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">Hello &amp; welcome </div>
                  <div class="font-alt mb-40 titan-title-size-4">Welcome to grade predictor app</div><a class="section-scroll btn btn-border-w btn-round" href="{{url_for('predictions.predict_form')}}">clicker pour voir</a>
                </div>
              </div>
            </li>
            <li class="bg-dark-30 bg-dark" style="background-image:{{url_for('static', filename='/images/section-9.jpg')}};">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-2">Cette Application vous predit vos resultat academique<br/>Pour des nouveaux étudiants
                  </div><a class="section-scroll btn btn-border-w btn-round" href="{{url_for('predictions.predict_form')}}">clicker pour voir</a>
                </div>
              </div>
            </li>
            <li class="bg-dark-30 bg-dark" style="background-image:{{url_for('static', filename='/images/section-10.jpg')}};">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">Nous faisons la magie moderne avec le data mining</div>
                  <div class="font-alt mb-40 titan-title-size-3">Nous sommes des génies des données</div><a class="section-scroll btn btn-border-w btn-round" href="{{url_for('predictions.predict_form')}}">clicker pour voir</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </section>
      <div class="main">
        <section class="module" id="about">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-sm-offset-2">
                <h2 class="module-title font-alt">Grade Predictor </h2>
                <div class="module-subtitle font-serif large-text">Nous avions analyser les données issues du système d'information UAT , et avons decouvert sur quoi est basée la resussite d'un étudiant dans une faculté à L'ULPGL et nous nous basons sur ces analyses pour vous prédire un resultat acceptable à 10% pret </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-2 col-sm-offset-5">
                <div class="large-text align-center"><a class="section-scroll" href="#services"><i class="fa fa-angle-down"></i></a></div>
              </div>
            </div>
          </div>
        </section>
        <hr class="divider-w">
        <section class="module" id="services">
          <div class="container">
            <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <h2 class="module-title font-alt">Notre Approche </h2>
                <div class="module-subtitle font-serif">Nous collectons les données issue du système UAT et le analysons</div>
              </div>
            </div>
            <div class="row multi-columns-row">
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="features-item">
                  <div class="features-icon"><span class="icon-lightbulb"></span></div>
                  <h3 class="features-title font-alt">Nos Decouvertes</h3>
                  <p>Sur base de ces données nous avions decouvert ce qui influence la reusite d'un étudiant dans une faculté</p>
                </div>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="features-item">
                  <div class="features-icon"><span class="icon-bike"></span></div>
                  <h3 class="features-title font-alt">Notre Demarche</h3>
                  <p>Nous avons effectuer la collecte , l'analyse et la modelisation selon la methodologie CRISP-DM</p>
                </div>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="features-item">
                  <div class="features-icon"><span class="icon-tools"></span></div>
                  <h3 class="features-title font-alt">Nos Outils</h3>
                  <p>Nous avons utiliser les differentes librairies de python pour arriver à notre resultat</p>
                </div>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="features-item">
                  <div class="features-icon"><span class="icon-gears"></span></div>
                  <h3 class="features-title font-alt">Notre Magie</h3>
                  <p>Nous utilisons des modèles du Machine Learning entre autre la regression lineaire et la regression logistique pour vous prédire le resultats fiables</p>
                </div>
              </div>
            </div>
          </div>
        </section>
{% endblock %}

GradePredictorApp/app/templates/predictions/forms.html
{% extends "base.html" %}
{% block title %}Predictor{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
        <section class="module">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-sm-offset-2">
                <h4 class="font-alt mb-0">Remplisssez et Voyez</h4>
                <hr class="divider-w mt-10 mb-20">
                <form id="predict-form" method="POST" action="{{url_for('predictions.predict')}}" class="form" role="form">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="form-group">
    <input class="typeahead form-control input-lg"  type="text" name="SCHOOL_RIGHT" id="SCHOOL_RIGHT" minlength="3" placeholder="(votre ecole de provenance)" data-provide="typeahead" autocomplete="off" required>
    </div>
    <div class="col-sm-8">
            <small id="error_school" class="text-danger">
            </small>
    </div>
<div class="form-group">
  <input class="typeahead form-control input-lg"
       name="OPTION_RIGHT" id="OPTION_RIGHT" data-provide="typeahead" placeholder="(choisissez votre option )" required>
  <div class="col-sm-8">
            <small id="error_option" class="text-danger">
            </small>
  </div>

</div>
<div class="form-group">
  <input  class="form-control input-lg" type="number" name="DIPPERC" min="50" max="100" id="DIPPERC" placeholder="(Poucentage du
    diplome )" required>
</div>
 <button class="btn btn-d btn-round  pull-right" type="submit"> Valider </button>
                </form>
              </div>
            </div>
          </div>
        </section>
 <script>
var csrf_token = "{{ csrf_token() }}";
// this will send a token each time before a session started
var form = document.getElementById("predict-form");

form.onsubmit = function (e) {
// stop the regular form submission
e.preventDefault();
data = {}
// collect the form data while iterating over the inputs
/**var formEntries = new FormData(form).entries();
var data = Object.assign(...Array.from(formEntries, ([x,y]) => ({[x]:y})));*/
$(this).serializeArray().map(function(x){data[x.name] = x.value;});
delete data["csrf_token"];
data["DIPPERC"] = data["DIPPERC"]/100.0
console.log(data);
// construct an HTTP request
var xhr = new XMLHttpRequest();
xhr.open(form.method, form.action, true);
xhr.setRequestHeader("X-CSRFToken", csrf_token);
xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
// send the collected data as JSON
xhr.send(JSON.stringify(data));

xhr.onloadend = function () {
  if (xhr.status == 200) {
    var results = JSON.parse(xhr.responseText)
    results = JSON.stringify(results)
    url = "{{url_for('predictions.view_results', results=results)}}"
    window.location = url + results
    } else {
    window.location = '/404'
    }

};
};
</script>
{% endblock %}

GradePredictorApp/app/templates/predictions/results.html
{% extends "base.html" %}
{% block title %} Results forms {% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
<section class="module">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-sm-offset-2">
                <h4 class="font-alt mb-0">Voici Nos Predictions</h4>
                <hr class="divider-w mt-10 mb-20">
                <h6 class="font-alt"><span class="fa fa-gavel"></span>
                  Droit
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FD']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-money"></span>
                  Economie
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FSEG']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-child"></span> Psycologie
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FPSE']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-book"></span>
                  Theologie
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FT']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-thermometer-quarter"></span> Medecine
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FM']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-venus-double"></span> Sante
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FSDC']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <h6 class="font-alt"><span class="fa fa-laptop"></span> Technologie
                </h6>
                <div class="progress">
                  <div class="progress-bar pb-dark" aria-valuenow="{{results['FSTA']}}" role="progressbar" aria-valuemin="0" aria-valuemax="100"><span class="font-alt"></span></div>
                </div>
                <a  href="{{url_for('predictions.predict_form')}}">
                  <button class="btn btn-d btn-round  pull-right" > Reesayer </button>
                </a>
                </div>
              </div>
            </div>
          </div>
        </section>
{% endblock %}